# Generated by Django 2.1.7 on 2019-04-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archived_Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(blank=True, max_length=200, null=True)),
                ('property_archived_on', models.DateTimeField(auto_now_add=True)),
                ('property_created_on', models.DateTimeField(blank=True, null=True)),
                ('propety_edited_on', models.DateTimeField(auto_now=True)),
                ('property_source', models.CharField(default='Unknown', max_length=200)),
                ('property_description', models.TextField(blank=True, default='', null=True)),
                ('property_link', models.URLField(blank=True, default='#', null=True)),
                ('property_image', models.FileField(blank=True, null=True, upload_to='')),
                ('property_cap_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('property_listing_price', models.PositiveIntegerField(blank=True, null=True)),
                ('property_lat', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('property_lon', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('property_notes', models.TextField(blank=True, default='None', null=True)),
            ],
            options={
                'verbose_name_plural': 'Archvied Properties',
                'default_permissions': ('delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Current_Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(blank=True, max_length=200, null=True)),
                ('property_created_on', models.DateTimeField(auto_now_add=True)),
                ('propety_edited_on', models.DateTimeField(auto_now=True)),
                ('property_source', models.CharField(default='Unknown', max_length=200)),
                ('property_description', models.TextField(blank=True, default='', null=True)),
                ('property_link', models.URLField(blank=True, default='#', null=True)),
                ('property_image', models.FileField(blank=True, null=True, upload_to='')),
                ('property_cap_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('property_listing_price', models.PositiveIntegerField(blank=True, null=True)),
                ('property_lat', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('property_lon', models.DecimalField(blank=True, decimal_places=20, max_digits=25, null=True)),
                ('property_notes', models.TextField(blank=True, default='None', null=True)),
            ],
            options={
                'verbose_name_plural': 'Current Properties',
            },
        ),
        migrations.CreateModel(
            name='DB_Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_on', models.DateTimeField(auto_now_add=True)),
                ('log', models.TextField(blank=True, default='None', null=True)),
            ],
            options={
                'default_permissions': 'view',
            },
        ),
        migrations.AlterUniqueTogether(
            name='current_property',
            unique_together={('property_name', 'property_description')},
        ),
        migrations.AlterUniqueTogether(
            name='archived_property',
            unique_together={('property_name', 'property_description')},
        ),
    ]
